apiVersion: v2
name: autokueue-alpha
description: A Helm chart for AutoKueue (Alpha) setup including Kueue, LocalQueue Creator, and default resources.
type: application
version: 0.1.0
appVersion: "0.1.0"
dependencies:
  - name: kueue
    version: "0.14.4"
    repository: "file://../kueue"
    condition: kueue.enabled
